#!/bin/bash
# Use dmenu/rofi to change runstate using systemd
# Adapted from i3pystatus wiki:
# https://github.com/enkore/i3pystatus/wiki/Shutdown-Menu

SYSTEMCTL="systemctl"
LOCKSCRIPT="$HOME/.i3/i3lock-extra -m pixelize"

# Systemctl required
if ! command -v $SYSTEMCTL >/dev/null 2>&1; then
    declare -A CHOICES
    CHOICES[Shutdown]="poweroff"
    CHOICES[Reboot]="reboot"
    CHOICES[Hibernate]="hibernate"
    CHOICES[Suspend]="suspend"
    CHOICES[Halt]="halt"
    CHOICES[Lock]="${LOCKSCRIPT}"
    CHOICES[Logout]="i3-msg exit"
    CHOICES[Cancel]=""
else
  CHOICES=(
    [Shutdown]="${SYSTEMCTL} poweroff"
    [Reboot]="${SYSTEMCTL} reboot"
    [Hibernate]="${SYSTEMCTL} hibernate"
    [Suspend]="${SYSTEMCTL} suspend"
    [Halt]="${SYSTEMCTL} halt"
    [Lock]="${LOCKSCRIPT}"
    [Logout]="i3-msg exit"
    [Cancel]=""
  )
fi

# names refer to associative array parameters
typeset -A CHOICES

NROWS=${#CHOICES[@]}

DMENU="dmenu -i -l $NROWS"
ROFI="rofi -dmenu -lines $NROWS -p Quit: -width -11 -bc white -location 3"

if command -v rofi >/dev/null 2>&1; then
  LAUNCHER=$ROFI
elif command -v dmenu >/dev/null 2>&1; then
  LAUNCHER=$DMENU
else
  exit 2
fi

CHOICE="$(printf '%s\n' "${!CHOICES[@]}" | sort | ${LAUNCHER})"

if [ $? -eq 0 ]; then
  ${CHOICES[$CHOICE]}
fi
